### ISSUE TITLE
GVideoOpening flag value missing on F10 screen

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#24]
(Possibly some other useful flags we added as well.)

**Comment by idealpersona** [comment]
Done for GVideoOpening in https://github.com/07th-mod/higurashi-assembly/commit/ee8a7acfbbb7b715ce9ad410572d527f076524d9

Includes a meaningful description for each value instead of just displaying 1, 2, etc.
0: Unset
1: Disabled
2: In-game
3: At launch + in-game

I think those descriptions are accurate?

**Comment by idealpersona** [comment]
Are any other flags valuable to be included in the F10 menu?  @tellowkrinkle @DoctorDiablo 

In order of priority: useful for a player, useful for us when debugging a player's issue, useful for development.
