### ISSUE TITLE
Support for Ryukishi sprites

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#33]
Aside from CG and CGAlt directories there will also be an OG directory. The key that swaps between graphics should cycle between all three modes now (if the OG directory exists - it won't for console arcs). Also this directory should behave the same as CG as in there will be no fallback if a file does not exist in OG. Some characters won't have sprites in the OG directory, we need to make sure that the drawing functions will simply do nothing and not crash the game in such case.

**Comment by enumag** [comment]
Note: This needs more discussion. While fallbacks are not desired for sprites in this case, they are desired for text screens etc.

**Comment by ItaloKnox** [comment]
So, my idea to fix the fallback issue is to make the OG directory work as the CGAlt directory, however, only a few folders should fallback instead of all of them. This could be either implemented as a whitelist or blacklist feature. 

Supposing we only want to avoid backgrounds, events, and sprites from being called from the CG folder, it would make more sense to implement a blacklist. If we're looking for only specific files, a whitelist might make sense in this case.

**Comment by enumag** [comment]
I'm not entirely sure what to do about CGs. All CGs are PS3 only except for one case in Meakashi that has both CGAlt and OG variant as well.

Another issue with CGs is that when there is a CG on the screen there are no sprites. But with OG the CGs won't be there so we might have to manually add the sprites there... Well only if we want perfection.

**Comment by ItaloKnox** [comment]
I've been iterating on this idea for a while after mixing a bunch of pitches from a lot of people together. My previous suggestion of implementing a whitelist/blacklist would take too much work to deal with, so I have a new idea.

There are two very important points we *need* to address and make sure they work:

* Ryukishi sprites with PS3 backgrounds (mode 1)
* Ryukishi sprites with photo backgrounds (mode 2)

Both cases are equally requested, and I agree doing more work to make sure they are viable is a good thing. Here's how I would make it:

We should consider the new sprites as some sort of dynamic CGAlt filtering. In mode 1, the DLL should only read the ``sprites`` folder (and a few other relevant folders if necessary), just like we handle Steam sprites. However, in mode 2, the DLL should consider all folders, including backgrounds this time.

I believe leaving the CGs is an okay compromise considering it requires script changes to bring back the sprites and backgrounds while they are playing. For characters that simply do not exist in the original release, I believe a small 1×1 empty PNG should be enough to deal with it. It's not ideal, but I don't believe it should be considered bloating the patch, since it uses so little space and are a minority.

**Comment by enumag** [comment]
This sounds quite reasonable. So for implementation details:

- We'll have an OG (Original Graphics) directory next to CG and CGAlt.
- The hotkey that currently swaps CG and CGAlt will instead cycle through 4 different modes:
  - PS3 Graphics (CG directory)
  - PS3 Graphics with MG sprites (CGAlt directory with CG as fallback)
  - Original Graphics (OG directory with CG as fallback)
  - Original Sprites (OG directory for `ModDrawCharacter` calls, CG for everything else)

This way it doesn't seem to be too difficult I think?

@idealpersona @tellowkrinkle or possibly @voodoochiledev, can you look into it?

**Comment by tellowkrinkle** [comment]
By the time the call gets down to loading the image it's hard to tell whether it came from a `ModDrawCharacter` call (you could pass an extra boolean through every function on the way to the `LoadTexture` call but that sounds terrible)
Instead, how's this: When it attempts to load a texture, the game consults an asset fallback list, which is an array of paths and returns the first path that points to a valid file
The four modes could be made by splitting the OG files into "OGBG" and "OGSprites" folders, then using the following lists:
- ["CG"]
- ["CGAlt", "CG"]
- ["OGBG", "OGSprites", "CG"]
- ["OGSprites", "CG"]

**Comment by enumag** [comment]
That could work. I think we should flatten it to:

- ["CG"]
- ["CGAlt", "CG"]
- ["OGBackgrounds", "OGSprites", "CG"]
- ["OGSprites", "CG"]

**Comment by enumag** [comment]
As in no subdirectories.

**Comment by tellowkrinkle** [comment]
Support should be added in a7a44a4c642904726b603a280a539217fd520816 for custom image directories
Add the following lines to `init.txt`:
```c
ModAddArtset("Console", "ゲーム機", "CG");
ModAddArtset("Remake", "リメーク", "CGAlt:CG");
ModAddArtset("Original", "オリジナル", "OGBackgrounds:OGSprites:CG");
ModAddArtset("Original (Sprites Only)", "オリジナル（立ち絵のみ）", "OGSprites:CG");
```
[Testing DLL (Onikakushi)](https://github.com/07th-mod/higurashi-assembly/files/3827166/Assembly-CSharp.dll.zip)

Note: You can add as many artsets as you want, the only hardcoded thing is that the first artset is the only one with lipsync support.  Current artset is viewable from the F10 menu (the config screen will highlight "Remake" if the selection is anything other than console).  As you might be able to guess, the arguments to the new function are English name, Japanese name, colon-separated path list.  Names are currently only used for the F10 screen but may be used for more things later.  The game will use the existing setup if you don't call `ModAddArtset` at all, but calling it once will allow only the one added (which should allow us to fix the lipsync-doesn't-work issue with console arcs).

**Comment by enumag** [comment]
Sounds good to me! Ok, next step we need to make the OG graphics packs. I'll try to work on that tomorrow.

**Comment by enumag** [comment]
Further progress is tracked in https://github.com/07th-mod/higurashi-patch-compiler/issues/54. For DLL I think this feature is complete so I'm closing this. I'll reopen it if we find some bug. Thanks for your hard work!
